//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marinichev619KingIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int Id { get; set; }
        public Nullable<int> IdShoppingCenter { get; set; }
        public Nullable<int> IdEmployee { get; set; }
        public string PovilionNum { get; set; }
        public Nullable<int> IdStatusRent { get; set; }
        public Nullable<System.DateTime> RentStart { get; set; }
        public Nullable<System.DateTime> RentEnd { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ShoppingCenter ShoppingCenter { get; set; }
        public virtual StatusRent StatusRent { get; set; }
    }
}
