//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marinichev619KingIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCenter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShoppingCenter()
        {
            this.Pavilion = new HashSet<Pavilion>();
            this.Rent = new HashSet<Rent>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> IdShoppingCenterStatus { get; set; }
        public Nullable<int> PovilionNum { get; set; }
        public Nullable<int> IdCity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<double> ValueAddedRatio { get; set; }
        public Nullable<int> Floor { get; set; }
        public string Image { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pavilion> Pavilion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent> Rent { get; set; }
        public virtual StatusShoppingCenter StatusShoppingCenter { get; set; }
    }
}
